server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          # uri: http://127.0.0.1:8081 # ??????? http??????,???
          uri: lb://user-service # ??????? lb??????????????
          predicates: # ???????????????????????
            - Path=/user/** # ?????????????/user???????
            - After=2022-01-03T11:05:00+08:00[Asia/Shanghai]
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**