server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          # uri: http://127.0.0.1:8081 # ??????? http??????,???
          uri: lb://user-service # ??????? lb??????????????
          predicates: # ???????????????????????
            - Path=/user/** # ?????????????/user???????
            - After=2022-01-03T11:05:00+08:00[Asia/Shanghai]
          filters: # ?????user-service????????
            - AddRequestHeader=Truth,GSP is best!

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
      default-filters: # ?????????????????
        - AddRequestHeader=Yes,GSP is very best!!!
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: # ???????????
              - "http://localhost:8090"
              - "http://www.leyou.com"
            allowedMethods: # ?????ajax?????
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # ????????????
            allowCredentials: true # ??????cookie
            maxAge: 360000 # ??????????