server:
  port: 8089
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8848
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
logging:
  level:
    com.gsp: debug
feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 每个路径最大连接数